SELECT [STATE]
      ,[YEAR]
      ,[ENROLL]
      ,[TOTAL_REVENUE]
      ,[TOTAL_EXPENDITURE]
      ,[A_A_A]
      ,[G12_A_A]
      ,[G09-G12_A_A]
      ,[G12_AM_F]
      ,[G12_AM_M]
      ,[G12_AS_F]
      ,[G12_AS_M]
      ,[G12_BL_F]
      ,[G12_BL_M]
      ,[G12_HI_F]
      ,[G12_HI_M]
      ,[G12_HP_F]
      ,[G12_HP_M]
      ,[G12_TR_F]
      ,[G12_TR_M]
      ,[G12_WH_F]
      ,[G12_WH_M]
FROM [Education].[dbo].[states_all_extended]
WHERE [ENROLL] != ' ' AND [A_A_A] != ' ' AND [G12_A_A] != ' ' AND [G09-G12_A_A] != ' ' AND [G09-G12_A_A] != ' ' AND [G12_AM_F] != ' ' AND [G12_AM_M] != ' ' AND [G12_AS_F] != ' ' AND [G12_AS_M] != ' ' AND [G12_BL_F] != ' ' AND [G12_BL_M] != ' ' AND [G12_HI_F] != ' ' AND [G12_HI_M] != ' ' AND [G12_HP_F] != ' ' AND [G12_HP_M] != ' ' AND [G12_TR_F] != ' ' AND [G12_TR_M] != ' ' AND [G12_WH_F] != ' ' AND [G12_WH_M] != ' '